name: Build RNNoise AppImage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build AppImage
      run: DOCKER_BUILDKIT=1 docker build . --output . -f Dockerfile.rnnoise
    - name: Rename AppImage
      id: rename-appimage
      run: |
        output=magic-mic_$(git rev-parse HEAD | cut -c 1-8)_rnnoise.AppImage
        echo "::set-output name=file::$output"
        mv magic-mic.AppImage "$output"
    - name: Upload AppImage
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.rename-appimage.outputs.file }}
        path: ${{ steps.rename-appimage.outputs.file }}
        if-no-files-found: error
